apiVersion: v1
kind: Service
metadata:
  name: teach-react-app
  labels:
    app: teach-react-app
spec:
  type: LoadBalancer
  selector:
    app: teach-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

 
